name: "build"
on:                                                                                                                                                                                                    
  push:                                                                                                                                                                                                
    branches:                                                                                                                                                                                          
      - master 

jobs:
  build:
    runs-on: "ubuntu-22.04"
    steps:
    - uses: "actions/checkout@v4"
    - run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
    - run: |
        sudo apt-get update && sudo apt-get install -y gcc-arm-linux-gnueabi binutils build-essential git flex bison libssl-dev bc axel libgmp-dev libmpc-dev jq
    - run: echo "ROOTFS_LATEST_URL=`curl -sL https://api.github.com/repos/linux-3ds/buildroot/releases | jq -r '.[].assets[].browser_download_url'`" >> $GITHUB_ENV
    - run: "axel ${ROOTFS_LATEST_URL}"
    - run: "make nintendo3ds_defconfig all"
      env:
        ARCH: "arm"
        CROSS_COMPILE: "arm-linux-gnueabi-"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: |
          arch/arm/boot/zImage
          arch/arm/boot/dts/nintendo3ds_ctr.dtb
          arch/arm/boot/dts/nintendo3ds_ktr.dtb

  release:
    name: Create Github Release
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Generate release tag
        id: tag
        run: |
            echo "RELEASE_TAG=Development build ${{ env.SHORT_SHA }}" >> "$GITHUB_ENV"
      
      - uses: actions/download-artifact@v4

      - name: Display structure of downloaded files
        run: ls -la 
      
      - uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          tag_name: ${{ env.RELEASE_TAG }}
          files: |
            arch/arm/boot/zImage
            arch/arm/boot/dts/nintendo3ds_ctr.dtb
            arch/arm/boot/dts/nintendo3ds_ktr.dtb
